[CM-987] - Migrating to Capacitor 3
Kommunicate-io/Kommunicate-Capacitor-Plugin pull request #7
Opened 2022-07-18 08:21 UTC by amntoppo

Migrated both Android and iOS

2022-07-18 09:15 UTC, Sathyan-Elangovan requested changes

2022-07-18 09:15 UTC, Sathyan-Elangovan commented on example/android/app/src/main/java/io/ionic/starter/MainActivity.java
> -    }
Why we have removed `FirebaseInstanceId.getInstance().getToken())`

2022-07-18 09:15 UTC, Sathyan-Elangovan commented on example/src/app/home/home.page.ts
> +const appId = "eb775c44211eb7719203f5664b27b59f"
Don't commit the app id. Remove this

2022-07-18 10:30 UTC, amntoppo commented on example/android/app/src/main/java/io/ionic/starter/MainActivity.java
> -    }
It was a log, which might fail and throw error in the sample app.

2022-07-18 10:30 UTC, amntoppo commented on example/src/app/home/home.page.ts
> +const appId = "eb775c44211eb7719203f5664b27b59f"
Updated

2022-07-19 02:12 UTC, Sathyan-Elangovan approved these changes

2022-07-20 04:19 UTC, merged